### PR TITLE
Replace iron-component-page with api-doc-viewer

### PR DESCRIPTION
**Pull request by Saulis**
Connects to https://github.com/vaadin/components-team-tasks/issues/239

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-form-layout/17)

### CODE REVIEW

**Comment by manolo** [comment]
Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-form-layout.html, line 68 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/17#-KhWjMSChk_Fz2t7FQp3:-KhWjMSChk_Fz2t7FQp4:bbko958) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/d043501ae3d5b154a1cc66b2d0b633d51fd8c42c/vaadin-form-layout.html#L68)):*
> ```HTML
>       /**
>       * `<vaadin-form-layout>` is a Polymer element providing configurable responsive layout for form elements.
>       *
> ```

Java doc convention the first line is indented one space left than the rest, mind to change it ?

```
  /*
   *
   */
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/17)*

**Comment by manolo** [comment]
Reviewed 2 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/17)*

**Comment by manolo** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-form-layout.html, line 68 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/17#-KhWjMSChk_Fz2t7FQp3:-KhXN-lkTc_f1VQi67ad:byluziy) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/d043501ae3d5b154a1cc66b2d0b633d51fd8c42c/vaadin-form-layout.html#L68)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Java doc convention the first line is indented one space left than the rest, mind to change it ?

```
  /*
   *
   */
```
</blockquote></details>

Sorry first line typo
```
 /**
  *
  */
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/17)*

**Comment by Saulis** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-form-layout.html, line 68 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/17#-KhWjMSChk_Fz2t7FQp3:-KhaqEUmSrYMwfVdy1Vq:b-896fix) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/d043501ae3d5b154a1cc66b2d0b633d51fd8c42c/vaadin-form-layout.html#L68)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Sorry first line typo
```
 /**
  *
  */
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/17)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/17#-:-KharFszUQPFBnWL_OnI:bnfp4nl)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/17#-:-KhaxIROme5aFUYdh2q_:bnfp4nl)*

**Pull request merged**
