### PR TITLE
Adapt demos to new vaadin site

### PR DESCRIPTION
**Pull request by manolo**
Connected to vaadin/components-team-tasks#273

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-form-layout/47)

### CODE REVIEW

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 3 of 8 files at r1, 7 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/47#-:-KuTh1GRsqa__0IVUERq:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[bower.json, line 41 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/47#-KuTiWAW7vdLLGD-NYLb:-KuTiWAW7vdLLGD-NYLc:blt0cr6) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/c31b0ac23e0ca18de2e374f12e589a51482aa770/bower.json#L41)):*
> ```JSON
>     "vaadin-demo-helpers": "vaadin/vaadin-demo-helpers"
>   },
>   "resolutions": {
> ```

Why is this block added? It installs just fine without it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/47)*

**Comment by manolo** [comment]
Review status: 5 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[bower.json, line 41 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/47#-KuTiWAW7vdLLGD-NYLb:-KuTkXQtD-EOXLYAC7xV:b-896fix) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/c31b0ac23e0ca18de2e374f12e589a51482aa770/bower.json#L41)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why is this block added? It installs just fine without it?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/47)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 3 of 8 files at r1, 3 of 7 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/47#-:-KuTmauiGqNzYJ7G0OS5:bnfp4nl)*

**Pull request merged**
