### PR TITLE
Add vertical margin in form item, form-item-row-gap CSS property

### LINKED ISSUE #30: Add default basic styles: "pretty, but simple"
Related Flowdock discussion: https://www.flowdock.com/app/vaadin/elements-team/threads/_PAcKU7U0EWmAm1stFTzwdmDo-Z

(This is the DX tests finding)

### PR DESCRIPTION
**Pull request by platosha**
Fixes #30

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-form-layout/37)

### CODE REVIEW

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 90 of 90 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/index.html, line 309 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/37#-Kj8J0EPWjcdrGO2N9cR:-Kj8J0EPWjcdrGO2N9cS:b-6mojkf) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/b651a5bb99d5ce9ca67d2bc847c1060cd0a59c51/demo/index.html#L309)):*
> ```HTML
>     <p>
>       The <code>&lt;paper-input&gt;</code> elements have builtin vertical spacing. Adding
>       margins with CSS is unnecessary.
> ```

Grammar: 'the' is not needed since we have the plural noun. Also, builtin -> built-in

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/37#-:-Kj8J_YdTqgnzygMQ5rN:bnfp4nl)*

**Comment by platosha** [comment]
Review status: 89 of 90 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/index.html, line 309 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/37#-Kj8J0EPWjcdrGO2N9cR:-Kj8LWMb4h6KgHB5aIc2:b-896fix) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/b651a5bb99d5ce9ca67d2bc847c1060cd0a59c51/demo/index.html#L309)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Grammar: 'the' is not needed since we have the plural noun. Also, builtin -> built-in
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/37)*

**Comment by limonte** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/37)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 89 of 90 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/37#-:-KjCtazgf58jrg_UCg9a:bnfp4nl)*

**Pull request merged**
