### PR TITLE
Add visual tests

### LINKED ISSUE #3: Visual regression testing
Part of epic vaadin/vaadin-core-elements#58

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #3

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-form-layout/10)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/visual/test.js, line 4 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/10#-KgSmlk0Zh9OpZwZ2IBP:-KgSmlk0Zh9OpZwZ2IBQ:b-ooxgdb) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/8b13810ab095ea5579ca384ac5bf7344e2ae75a7/test/visual/test.js#L4)):*
> ```JavaScript
> 
>   var demos = [
>     {name: 'index', snippetCount: 2}
> ```

I would add a description to each test so as dir structure makes more sense than index-1 index-2 ...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/10)*

**Comment by tomivirkki** [comment]
*[test/visual/test.js, line 4 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/10#-KgSmlk0Zh9OpZwZ2IBP:-KgTPUph7v9yV9vOgQli:bcvjgzp) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/8b13810ab095ea5579ca384ac5bf7344e2ae75a7/test/visual/test.js#L4)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I would add a description to each test so as dir structure makes more sense than index-1 index-2 ...
</blockquote></details>

Good idea. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/10)*

**Comment by limonte** [comment]
something is wrong with `paper-input/default/edge.png`. The 1st field styling looks like focused and there's something like a cursor in the 3rd input

---

Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/10#-:-KgTez4pn5FDUyLxj1Mb:b-ssxsff)*

**Comment by tomivirkki** [comment]
That's how the demo appears if you open it with Edge

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/10#-:-KgTfJnZ3bbAvGRDfOrN:b-p3h3is)*

**Comment by limonte** [comment]
Weird :) But not in scope of this PR :lgtm: 

---

Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/10#-:-KgTfe3UJMLbAopl37wv:bcde3ld)*

**Comment by manolo** [comment]
build is failing, something missing or you need to update screenshots?

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/10#-:-KgTjlsdsh4m4sBDJ-KO:b-ra7187)*

**Comment by limonte** [comment]
From my experience, it's better to have wait time 5s to have more stable results. I added the commit and now tests are passing, @tomivirkki please pull the updates.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/10#-:-KgUb7gJRoWlIl0lLlnx:b-mntwix)*

**Comment by tomivirkki** [comment]
I don't think it was the wait time that caused the test failures but the blinking caret. Your commit includes a screenshot with the caret hidden while the previous reference image had it visible. Need to look into why Edge focuses the demo input automatically.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/10#-:-KgUfnDNHE1T64K7or87:b-kaqqmz)*

**Comment by manolo** [comment]
Yes, that is the problem, in vaadin-text-field happened the same, finally the only working solution was either configure a no size font (https://github.com/vaadin/vaadin-text-field/blob/master/test/visual/default.html#L22)  (or not focus the input but change the styles setting the focused attribute manually (https://github.com/vaadin/vaadin-text-field/blob/master/test/visual/styling.html#L90). I played with other options like a layer covering the cursor, etc, but does not work in IE.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/10#-:-KgXlkbBXBKYQ-oNS3Fd:b-qmp0xm)*

**Comment by limonte** [comment]
That input should not be focused so there should not be any cursor caret. Also, first input looks like focused but it should not be. Those are issues related to Edge, not to this PR.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/10#-:-KgXr2U1maFLmCCWXuwl:b-rgnqq2)*

**Pull request merged**
