### PR TITLE
Add styling demo

### LINKED ISSUE #16: Theming Example
- Main purpose is to document using the all "parts" for theming.
- List all the parts in the API docs (vs. the old CSS mixins)
- Let's use Bootstrap as inspiration for visual end result
- Not sure if this is relevant at all because label is in the light DOM and doesn't need a part? Hmm...

### PR DESCRIPTION
**Pull request by platosha**
Fixes #16

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-form-layout/20)

### CODE REVIEW

**Comment by manolo** [comment]
Reviewed 8 of 174 files at r1.
Review status: 7 of 168 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/styling.html, line 31 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/20#-Kib6XAftZilh95ZiX5B:-Kib6XAftZilh95ZiX5C:bbji5qc) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/537589bc5239aa05991cfa6432003f94bb251994/demo/styling.html#L31)):*
> ```HTML
>     <demo-snippet>
>       <template>
>         <dom-module id="form-layout-bootstrap-styles" theme-for="vaadin-form-layout">
> ```

why not unify both modules? so as we only have one theming module demonstrating that everything can be merged in one file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/20)*

**Comment by platosha** [comment]
Review status: 7 of 168 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/styling.html, line 31 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/20#-Kib6XAftZilh95ZiX5B:-KidXiEyl_u62xSkntgy:brzyue2) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/537589bc5239aa05991cfa6432003f94bb251994/demo/styling.html#L31)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

why not unify both modules? so as we only have one theming module demonstrating that everything can be merged in one file?
</blockquote></details>

As this is a doc example code, it is more appropriate to clarify what belongs where. These styles belong to different components.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/20)*

**Comment by tomivirkki** [comment]
A _lot_ more than "Add styling demo" in this PR but :lgtm: 

---

Reviewed 174 of 174 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/20#-:-Kie-Wf-Z1W1gqZdHAJ3:b-jm1tsp)*

**Comment by limonte** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/20#-:-Kie86lCdydpS55S_w-F:bnfp4nl)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/styling.html, line 31 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/20#-Kib6XAftZilh95ZiX5B:-KihwdExfyW38J2ZiAFx:bu7o1oa) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/537589bc5239aa05991cfa6432003f94bb251994/demo/styling.html#L31)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

As this is a doc example code, it is more appropriate to clarify what belongs where. These styles belong to different components.
</blockquote></details>

Well, if I were a theme designer I would like to theme the form-layout as a whole, since the item element is part of it, no directly usable in other element. Anyways not blocker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/20)*

**Comment by manolo** [comment]
Reviewed 166 of 174 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/20)*

**Pull request merged**
