### PR TITLE
Replace “columns” property with “responsiveSteps” array

### LINKED ISSUE #22: Change columns property syntax to more readable
Most probably we need to brainstorm a new syntax for custom responsive steps.

The current one is "funny" and "WAT". It's hard to read and interpret it.

(This is the DX tests finding)

### PR DESCRIPTION
**Pull request by platosha**
Fixes #22

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-form-layout/38)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 36 files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/index.html, line 145 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/38#-KjMBOIdJtLLxU0wbS49:-KjMBOIedg3yU1nkbKoj:b-uux4q) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/c7b95271b3537dd1d8365860770e7ba015f40d55/demo/index.html#L145)):*
> ```HTML
>       <script type="text/html" slot="source">
>         <vaadin-form-layout
>             responsive-steps='[
> ```

To me, this syntax still seems weak.

The user has a lot of constrains in the declarative
 - Use single quotes in order to write json as string.
 - Split the attribute value if he wants to leave a readable code.
 - Configure linters for not complain

We also need to hack polymer demo helpers because they dont consider this use case, and we have to document the object in jsdoc blocks instead of the easiness of documenting elements.
Actually the only point of having this way is that it's makes easier the imperative implementation which probably might be better for Flow.

IMO, something like this would make more sense, the user writes the same, and he has real declarative syntax check in their IDE. 

```
<vfl-column min-width="0" columns="2" />
<vfl-column min-width="30em" columns="3" />
```

Not a blocker, just ideas for thinking about.

---

*[demo/nice-demo-snippet.html, line 32 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/38#-KjMIa2JaBCHIp7UWpez:-KjMIa2JaBCHIp7UWpf-:b-g6o7aw) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/c7b95271b3537dd1d8365860770e7ba015f40d55/demo/nice-demo-snippet.html#L32)):*
> ```HTML
> -->
> 
> <dom-module id="nice-demo-snippet">
> ```

I'm against implementing and maintain our own demo-snippet, actually, what is bad on showing the json value in one line?
If we go with this, it should be in the elements-demo-resources repo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/38)*

**Comment by manolo** [comment]
Review status: 0 of 36 files reviewed at latest revision, 4 unresolved discussions.

---

*[bower.json, line 33 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/38#-KjMJko-YLlIewyoZ7Tz:-KjMJko-YLlIewyoZ7U-:b-sa1q0h) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/c7b95271b3537dd1d8365860770e7ba015f40d55/bower.json#L33)):*
> ```JSON
>     "vaadin-text-field": "vaadin/vaadin-text-field",
>     "paper-input": "polymerelements/paper-input#2.0-preview",
>     "prism-element": "polymerelements/prism-element#2.0-preview",
> ```

They are already dependencies of iron-demo-helpers, do we need to specify  here? they are dev dependencies and do not aport any interesting info for the reader

---

*[demo/index.html, line 106 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/38#-KjMKix27Aiv6ht1gWYt:-KjMKix27Aiv6ht1gWYu:bgwpgs6) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/c7b95271b3537dd1d8365860770e7ba015f40d55/demo/index.html#L106)):*
> ```HTML
>     -->
>     <nice-demo-snippet>
>       <script type="text/html" slot="source">
> ```

what is this script type hack for? if we don't want the content be rendered, the template seems the tag for that, or am i missing something ? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/38)*

**Comment by platosha** [comment]
Review status: 0 of 36 files reviewed at latest revision, 4 unresolved discussions.

---

*[bower.json, line 33 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/38#-KjMJko-YLlIewyoZ7Tz:-KjMLMFrgV5h5YUTkTkR:b-tuqey3) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/c7b95271b3537dd1d8365860770e7ba015f40d55/bower.json#L33)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

They are already dependencies of iron-demo-helpers, do we need to specify  here? they are dev dependencies and do not aport any interesting info for the reader
</blockquote></details>

`<nice-demo-snippet>` uses them directly. Relying on transitive dependencies is not good in this case.

Once we move `<nice-demo-snippet>` somewhere else, we can move this dependencies as well.

---

*[demo/index.html, line 106 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/38#-KjMKix27Aiv6ht1gWYt:-KjMLkLntspLKICBh57Y:by495qw) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/c7b95271b3537dd1d8365860770e7ba015f40d55/demo/index.html#L106)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

what is this script type hack for? if we don't want the content be rendered, the template seems the tag for that, or am i missing something ? 
</blockquote></details>

See the comment above, and more in `demo/nice-demo-snippet.html`.

`<template>` opens up the source to the browser’s parser. This does not matter for the majority of examples, but pretty bad for some of them, because it eats up line breaks and quotation symbols.

Using `<script>` allows to leave the formatting as it is, and make JSON values readable in the code snippets of the demos.

---

*[demo/nice-demo-snippet.html, line 32 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/38#-KjMIa2JaBCHIp7UWpez:-KjMQKbsLpxfX4YWvhL1:b-id8rje) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/c7b95271b3537dd1d8365860770e7ba015f40d55/demo/nice-demo-snippet.html#L32)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I'm against implementing and maintain our own demo-snippet, actually, what is bad on showing the json value in one line?
If we go with this, it should be in the elements-demo-resources repo
</blockquote></details>

Note that, actually, it’s not the first time where `<demo-snippet>` performs bad. Every time we want to split a long attribute list on multiple lines, line breaks disappear. We have JS Array and Object properties in the other elements, like `items` in `<vaadin-combo-box>`. `<nice-demo-snippet>` has its niche in the other elements, I believe.

OK to move to the `elements-demo-resources`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/38)*

**Comment by tomivirkki** [comment]
:lgtm: The demos could use `unresolved` attribute at `<body>` tag though. The initialization is really jumpy on polyfilled browsers.

---

Reviewed 37 of 37 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/38#-:-KjMWhJKjRxMUT2ghc9-:b-9lti2m)*

**Comment by platosha** [comment]
@tomivirkki done.

---

Review status: 31 of 35 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/38#-:-KjMahafu64B_zZOuEg2:b-9ocdiw)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 37 files at r1, 5 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/38)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/38)*

**Comment by manolo** [comment]
Giving my :lgtm: because the implementation works, it's clearer than before, and I don't think I should block this if the code works.
But still convinced that this PR does not aims the best DX in declarative language. With the penalty of introducing a lot of hacks in the component (extra component for demos abandoning polymer standards, extra work in jsdocs comments, etc). I indeed think this should be prototyped in a different way.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/38#-:-KjMplM0s7hRBDNU1V81:b-h85vt5)*

**Pull request merged**
