### PR TITLE
Add light DOM children distribution

### PR DESCRIPTION
**Pull request by platosha**
Fixes vaadin/components-team-tasks#229

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-form-layout/1)

### CODE REVIEW

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/1#-:-KbTu0BKyOPxiuRR7FVO:bnfp4nl)*

**Comment by limonte** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[bower.json, line 33 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/1#-KbU0uH-oID0NurMrVTw:-KbU0uH-oID0NurMrVTx:bbhh67h) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/95e6369bf3b07d29e6a4bcf49c24f8e2d32606cc/bower.json#L33)):*
> ```JSON
>     "iron-demo-helpers": "polymerelements/iron-demo-helpers#2.0-preview",
>     "vaadin-input": "Vaadin/vaadin-input",
>     "paper-input": "PolymerElements/paper-input#2.0-preview"
> ```

`vaadin/` and `Vaadin/`
`polymerelements/` and `PolymerElements/`

more consistent, please :)

---

*[demo/common.html, line 8 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/1#-KbU102RfWMLrEMZu1vW:-KbU102RfWMLrEMZu1vX:b-bnjdxl) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/95e6369bf3b07d29e6a4bcf49c24f8e2d32606cc/demo/common.html#L8)):*
> ```HTML
> 
> <link rel="import" href="../../elements-demo-resources/common.html">
> 
> ```

I'm wondering if it's necessary to encode dashes inside the HTML comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/1)*

**Comment by platosha** [comment]
Review status: 5 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[bower.json, line 33 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/1#-KbU0uH-oID0NurMrVTw:-KbUEoiqMetnnZ0KyZ6z:b-896fix) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/95e6369bf3b07d29e6a4bcf49c24f8e2d32606cc/bower.json#L33)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

`vaadin/` and `Vaadin/`
`polymerelements/` and `PolymerElements/`

more consistent, please :)
</blockquote></details>

Done.

---

*[demo/common.html, line 8 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/1#-KbU102RfWMLrEMZu1vW:-KbUE06XEJaYgOD_oqgQ:b-9j5w47) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/95e6369bf3b07d29e6a4bcf49c24f8e2d32606cc/demo/common.html#L8)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

I'm wondering if it's necessary to encode dashes inside the HTML comment?
</blockquote></details>

Maybe not, that’s what my vim did there.

Replaced with plain dashes to simplify future uncommenting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/1)*

**Comment by limonte** [comment]
:lgtm:

---

Review status: 5 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/1#-:-KbUFjCuBZMzCbvmMkQB:bnfp4nl)*

**Comment by tomivirkki** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/1)*

**Pull request merged**
