### PR TITLE
Add label support with <vaadin-form-item> element

### LINKED ISSUE #9: Label
Current specs by @jouni

### Form layout item can be given a label

For situations where the field doesn’t have built-in support for the responsive label alignment (left-of-the-field by default, top-of-the-field after a breakpoint or opt-in), the developer can add a wrapper element around the field and provide a label element inside the wrapper.

This label is for visual purposes only at this point, so no accessibility bindings between the label and the field are made. We already prototyped this a bit, but we couldn’t find a nice way. That prototyping should be continued later.

**API proposal:**
```html
<vaadin-form-layout>
  <!-- 
    Providing a responsive label for a field which does not have built-in integration 
  -->
  <vaadin-form-item>
    <!-- 
      Slot for the responsive label. If the developer wants this to be announced by 
      the screen reader, they need to add that themselves.
    -->
    <label slot="label">Send newsletter</label>

    <!-- 
      Any elements without a named slot are placed inside the "field column" 
    -->
    <label><input type="radio" name="newsletter"> Daily</label>
    <label><input type="radio" name="newsletter"> Weekly</label>
    <label><input type="radio" name="newsletter"> Monthly</label>
    <label><input type="radio" name="newsletter"> Never</label>
  </vaadin-form-item>

  <!-- 
    Text field takes the entire column width. Label behaviour is default — on top, floating in Material theme
  -->
  <vaadin-text-field label="Name"></vaadin-text-field>
</vaadin-form-layout>
```

### The position and size/width of the label are controlled by the form layout

By default, the label is placed on the left side of the field (or right side for RTL languages). On certain breakpoints the labels should be on top of the field. The breakpoints that wrap the label on top are specified in the `columns` property (see #4) with a keyword, for example:

```html
<vaadin-form-layout columns="1 labels-on-top, 20em 1, 40em 2 labels-on-top, 60em 2">
  ...
</vaadin-form-layout>
```

Meaning:
- \>= 0: 1 column, labels on top
- \>= 20em: 1 column, labels aside
- \>= 40em: 2 columns, labels on top
- \>= 60em: 2 columns, labels aside

(APIs can change)

The “label column” width is controlled by the form-layout, and it can be a “fixed” width at this point and not affected by the length of the labels.

The width can be controlled with a CSS custom property (e.g. `--vaadin-form-item-label-width`). The default width is `8em`.

The gap between the label and the field can be controlled with a CSS custom property (e.g. `--vaadin-form-item-label-gap`). The default gap is `1em`.

### PR DESCRIPTION
**Pull request by platosha**
Fixes #9

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-form-layout/19)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 113 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-form-item.html, line 52 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19#-Ki5JrULj_tT4sC6TZHC:-Ki5JrULj_tT4sC6TZHD:bpstjrs) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/0aaf3ce900c1c6a791f8dbbd63a2ed171129e2b4/vaadin-form-item.html#L52)):*
> ```HTML
>       }
>     </style>
>     <div id="label" part="label" on-click="_onLabelClick">
> ```

The shadow parts should be documented.

---

*[vaadin-form-item.html, line 130 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19#-Ki5KMx5CSJb0uda77et:-Ki5KMx5CSJb0uda77eu:by53h9n) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/0aaf3ce900c1c6a791f8dbbd63a2ed171129e2b4/vaadin-form-item.html#L130)):*
> ```HTML
> 
>         _onLabelClick(e) {
>           // No `Array.prototype.find` in MSIE :-(
> ```

You could use `reduce()` instead of `find()` to make this a two-liner:
```
const firstContentElementChild = this.$.contentSlot.assignedNodes()
  .reduce((arr, el) => el.nodeType === Node.ELEMENT_NODE ? arr.concat(el) : arr, [])[0];
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19)*

**Comment by tomivirkki** [comment]
*[test/visual/form-layout.html, line 160 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19#-Ki5MdH8AvEL3hfb7v5G:-Ki5MdH9hQosX4CxazaI:b-usiv6t) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/0aaf3ce900c1c6a791f8dbbd63a2ed171129e2b4/test/visual/form-layout.html#L160)):*
> ```HTML
>   <script>
>     addEventListener('WebComponentsReady', function() {
>       Polymer({is: 'my-form'});
> ```

Why use Polymer 1 way here to define the custom element?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19)*

**Comment by platosha** [comment]
Review status: 0 of 114 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-form-item.html, line 52 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19#-Ki5JrULj_tT4sC6TZHC:-Ki5ieCgb7gfzlDukM8e:b-896fix) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/0aaf3ce900c1c6a791f8dbbd63a2ed171129e2b4/vaadin-form-item.html#L52)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The shadow parts should be documented.
</blockquote></details>

Done.

---

*[vaadin-form-item.html, line 130 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19#-Ki5KMx5CSJb0uda77et:-Ki5ijMmsgwMPvxuDB-G:b-896fix) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/0aaf3ce900c1c6a791f8dbbd63a2ed171129e2b4/vaadin-form-item.html#L130)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

You could use `reduce()` instead of `find()` to make this a two-liner:
```
const firstContentElementChild = this.$.contentSlot.assignedNodes()
  .reduce((arr, el) => el.nodeType === Node.ELEMENT_NODE ? arr.concat(el) : arr, [])[0];
```
</blockquote></details>

Done.

---

*[test/visual/form-layout.html, line 160 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19#-Ki5MdH8AvEL3hfb7v5G:-Ki5jFuJPX6Cv-rr5qjn:b-qrts6l) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/0aaf3ce900c1c6a791f8dbbd63a2ed171129e2b4/test/visual/form-layout.html#L160)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why use Polymer 1 way here to define the custom element?
</blockquote></details>

Shorter, 1LOC vs 3LOC. This is the same code as in demo, where it matters to keep the boilerplate at minimal.

Changed to P2 syntax in both places.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19)*

**Comment by Saulis** [comment]
Reviewed 108 of 113 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-form-item.html, line 96 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19#-Ki5J0kf3p4uwqCFUtoO:-Ki5J0kf3p4uwqCFUtoP:b-qn7ue4) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/0aaf3ce900c1c6a791f8dbbd63a2ed171129e2b4/vaadin-form-item.html#L96)):*
> ```HTML
>        * By default, `<vaadin-form-item>` does not manipulate the width of the slotted
>        * input elements. Optionally you can stretch the child input element to fill
>        * the avaiable width for the input content by applying the `full-width` classname:
> ```

available

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19)*

**Comment by platosha** [comment]
Review status: 112 of 114 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-form-item.html, line 96 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19#-Ki5J0kf3p4uwqCFUtoO:-KiA6RJdjkrwykwDFr3a:b-896fix) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/0aaf3ce900c1c6a791f8dbbd63a2ed171129e2b4/vaadin-form-item.html#L96)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

available
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19#-:-KiA6mWzdjalDcx1fGuI:bnfp4nl)*

**Comment by manolo** [comment]
Reviewed 3 of 113 files at r1, 3 of 6 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[vaadin-form-item.html, line 83 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19#-KiAAGvCBPSvm2UOE3WQ:-KiAAGvCBPSvm2UOE3WR:br7zhti) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/c227ce2e3a876c0e49d53bf058fd370a0c6ebc5b/vaadin-form-item.html#L83)):*
> ```HTML
>        * ```html
>        * <vaadin-form-item label-on-top>
>        *   <label slot="label">Label on top</label>
> ```

It's not clear in the doc if the user can use any element as label.

---

*[vaadin-form-item.html, line 102 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19#-KiA9HIYLhBMlO0d9jF1:-KiA9HIYLhBMlO0d9jF2:buhq1i3) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/c227ce2e3a876c0e49d53bf058fd370a0c6ebc5b/vaadin-form-item.html#L102)):*
> ```HTML
>        * <vaadin-form-item>
>        *   <label slot="label">Label</label>
>        *   <input class="full-width">
> ```

in other contexts I have seen this class as `fit`, it might be more meaningful, just for thinking. Not blocker

---

*[vaadin-form-item.html, line 110 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19#-KiA9bYTVwJ-kOpsI4rA:-KiA9bYTVwJ-kOpsI4rB:bjp7o5t) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/c227ce2e3a876c0e49d53bf058fd370a0c6ebc5b/vaadin-form-item.html#L110)):*
> ```HTML
>        * The `label-on-top` host attribute can be used to target the label on top state:
>        *
>        * <pre><code>
> ```

Why not using here markdown like in the rest of the java-doc block?

---

*[vaadin-form-layout.html, line 188 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19#-KiAAgz0d18VRTHrdrhs:-KiAAgz0d18VRTHrdrht:bjliqp9) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/c227ce2e3a876c0e49d53bf058fd370a0c6ebc5b/vaadin-form-layout.html#L188)):*
> ```HTML
>              * #### Formal syntax
>              *
>              *     <responsive-step> [ , <responsive-step> ]*
> ```

why these html blocks are not enclosed by triple backtick, you are already using md tags

---

*[vaadin-form-layout.html, line 245 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19#-KiABQ9bCGhRNaH60mVl:-KiABQ9bCGhRNaH60mVm:b-mpaj2n) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/c227ce2e3a876c0e49d53bf058fd370a0c6ebc5b/vaadin-form-layout.html#L245)):*
> ```HTML
>             columns: {
>               type: String,
>               value: '1 labels-on-top, 20em 1, 40em 2',
> ```

Why the syntax is not using the camelized form? hyphen looks fine for attribute names, but not for this case, it just my feeling

---

*[demo/index.html, line 26 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19#-KiACgsczvS-2rvc2Xwb:-KiACgsczvS-2rvc2Xwc:b-e310mg) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/c227ce2e3a876c0e49d53bf058fd370a0c6ebc5b/demo/index.html#L26)):*
> ```HTML
>       <template>
>         <vaadin-form-layout>
> ```

IMO, the easier way to use the form-layout is just adding elements without wrapping with the form-item.
Reading the demos it seems that we are encouraging to use the form-item always.
I would leave the demos as they were, and add a couple of demos showing how to use the feature of labels managed by the form-layout.

If we actually want the user to use the form-item element as the preferred, we should disallow the other way

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19)*

**Comment by platosha** [comment]
Review status: 56 of 114 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-form-item.html, line 83 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19#-KiAAGvCBPSvm2UOE3WQ:-KiAaRM6cDx-TJA2WehX:b-896fix) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/c227ce2e3a876c0e49d53bf058fd370a0c6ebc5b/vaadin-form-item.html#L83)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

It's not clear in the doc if the user can use any element as label.
</blockquote></details>

Done.

---

*[vaadin-form-item.html, line 110 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19#-KiA9bYTVwJ-kOpsI4rA:-KiAKhibUFVhj6pPA-ZB:b2o9cyt) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/c227ce2e3a876c0e49d53bf058fd370a0c6ebc5b/vaadin-form-item.html#L110)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Why not using here markdown like in the rest of the java-doc block?
</blockquote></details>

I want to add a comment inside `<style>` in the example block.

CSS only supports block comments, `/* ... */`. 

If I write `*/` literally, it is parsed as end of JSdoc comment block, and gives syntax errors in the next lines. I have to break `*/` from JS parsing somehow.

HTML entities are broken with markdown syntax, code highlighting wraps `;` with spans, which makes `&#42;` produces literal output instead of an asterisk in browsers.

With HTML `<pre><code>`, highlighting does not work, but HTML entities do work.

Another option is to use some Unicode magic characters, such as a zero-width space between `*/`. Not sure which way is better. Invisible spaces are too easy to lose when maintaining...

---

*[vaadin-form-layout.html, line 188 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19#-KiAAgz0d18VRTHrdrhs:-KiAO8n5jhioQg3OAW6H:b-7hh5i8) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/c227ce2e3a876c0e49d53bf058fd370a0c6ebc5b/vaadin-form-layout.html#L188)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

why these html blocks are not enclosed by triple backtick, you are already using md tags
</blockquote></details>

This line is not HTML. This is just a monospace technical spec language “code” block, resembling CSS standards syntax.

+4 spaces indentation defines a code block in markdown, the same way as triple backticks do, but does not take separate line. While the end result is the same, without the backticks code looks cleaner here. 

Note, that unlike this line, the `<dl> <dt> <dd>` tags below is a markup, not a code block. `<dl>` is not supported by Markdown, using HTML therefore.

---

*[vaadin-form-layout.html, line 245 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19#-KiABQ9bCGhRNaH60mVl:-KiAQa21bZpeVB3nWRlv:b-z7jb3b) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/c227ce2e3a876c0e49d53bf058fd370a0c6ebc5b/vaadin-form-layout.html#L245)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Why the syntax is not using the camelized form? hyphen looks fine for attribute names, but not for this case, it just my feeling
</blockquote></details>

That was defined in the ticket.

Could be changed if DX tests reveal issues.

---

*[demo/index.html, line 26 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19#-KiACgsczvS-2rvc2Xwb:-KiAReeaihvTbMlfP4eY:byceipb) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/c227ce2e3a876c0e49d53bf058fd370a0c6ebc5b/demo/index.html#L26)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

IMO, the easier way to use the form-layout is just adding elements without wrapping with the form-item.
Reading the demos it seems that we are encouraging to use the form-item always.
I would leave the demos as they were, and add a couple of demos showing how to use the feature of labels managed by the form-layout.

If we actually want the user to use the form-item element as the preferred, we should disallow the other way
</blockquote></details>

Previously, there was no `vaadin-form-item` element.

Now, having the label, making demos not to use the form-item effectively hides the label positioning / wrapping feature from the users.

Label is a core feature of the form layout, so it has to be promoted in the demos, that’s why they are form-item based now. Every other demo now demonstrate both the demo feature and the label behavior.

I’m not in favour of disallowing not wrapping:

1. Disallowing using any markup requires more code, since `<slot>` does not provide element type filtering out-of-the-box in Shadow DOM v1.

2. I don’t see any value in disallowing. On the other hand, having any elements allowed is beneficial. The users who don’t need labels aside can avoid using form-item altogether, and thus have less HTML imports, less deep DOM and less markup.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19)*

**Comment by manolo** [comment]
Review status: 56 of 114 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-form-layout.html, line 188 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19#-KiAAgz0d18VRTHrdrhs:-KiAfN3FvUO16tTbuevo:b-q8ilnv) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/c227ce2e3a876c0e49d53bf058fd370a0c6ebc5b/vaadin-form-layout.html#L188)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

This line is not HTML. This is just a monospace technical spec language “code” block, resembling CSS standards syntax.

+4 spaces indentation defines a code block in markdown, the same way as triple backticks do, but does not take separate line. While the end result is the same, without the backticks code looks cleaner here. 

Note, that unlike this line, the `<dl> <dt> <dd>` tags below is a markup, not a code block. `<dl>` is not supported by Markdown, using HTML therefore.
</blockquote></details>

gotcha

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 51 of 113 files at r1, 1 of 6 files at r2, 58 of 58 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/19#-:-KiAfwoRU3dz1vEm1ews:bnfp4nl)*

**Pull request merged**
