### PR TITLE
API change: labelsOnTop: boolean to labelsPosition: string

### LINKED ISSUE #40: API Change: labelsOnTop: boolean to labelsPosition: string
As discussed with colleagues, `labelsOnTop` boolean flag is confusing and not future-compatible.

Let us change to `labelsPosition: <"top"|"aside">` string instead.

### PR DESCRIPTION
**Pull request by platosha**
Fixes #40

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-form-layout/41)

### CODE REVIEW

**Comment by limonte** [comment]
It's labelPosition, not labelsPosition (singular)

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/41#-:-KkPe86yBlQC5cP8aXDT:b-sznwm0)*

**Comment by limonte** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-form-layout.html, line 336 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/41#-KkPwmYb-RpqzUQIAHgd:-KkPwmYb-RpqzUQIAHge:bcisvaw) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/7cc7254b9660f5a0d510da1849a5cb1c9ae67e28/vaadin-form-layout.html#L336)):*
> ```HTML
>               }
> 
>               if (step.labelsPosition !== undefined && ['aside', 'top'].indexOf(step.labelsPosition) === -1) {
> ```

`step.labelsPosition !== undefined` check is unnecessary here

---

*[demo/index.html, line 181 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/41#-KkPwvAwibJrzvK8FK_n:-KkPwvAwibJrzvK8FK_o:b7vvbdk) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/7cc7254b9660f5a0d510da1849a5cb1c9ae67e28/demo/index.html#L181)):*
> ```HTML
>       <dd>Default value. Labels are positioned aside the input fields.</dd>
>       <dt>top</dt>
>       <dd>Lables are positioned above the input fields.</dd>
> ```

typo 'Labels'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/41)*

**Comment by platosha** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-form-layout.html, line 336 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/41#-KkPwmYb-RpqzUQIAHgd:-KkPxSwT1d-oBQsHQeUj:bwq2ypq) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/7cc7254b9660f5a0d510da1849a5cb1c9ae67e28/vaadin-form-layout.html#L336)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

`step.labelsPosition !== undefined` check is unnecessary here
</blockquote></details>

It is. The key is entirely optional, so `undefined` is a **valid** value.

I could add it into the valid values array if you prefer, just doubt if it is better.

---

*[demo/index.html, line 181 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/41#-KkPwvAwibJrzvK8FK_n:-KkPxqjf3rZV-3RLGl87:b-896fix) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/7cc7254b9660f5a0d510da1849a5cb1c9ae67e28/demo/index.html#L181)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

typo 'Labels'
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/41)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-form-layout.html, line 336 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/41#-KkPwmYb-RpqzUQIAHgd:-KkPy55BgiOksIAlqIo4:byr4flj) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/7cc7254b9660f5a0d510da1849a5cb1c9ae67e28/vaadin-form-layout.html#L336)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

It is. The key is entirely optional, so `undefined` is a **valid** value.

I could add it into the valid values array if you prefer, just doubt if it is better.
</blockquote></details>

Right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/41#-:-KkPyKeBbCXI4fAlsbW9:bnfp4nl)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-form-layout.html, line 187 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/41#-KkQXciHQDj4zaFzNTyd:-KkQXciHQDj4zaFzNTye:bctn7kp) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/c6ea74d1d2678c911541c10fa5d9b6f30942908f/vaadin-form-layout.html#L187)):*
> ```HTML
>              * Format: array of objects, each object defines one responsive step
>              * with `minWidth` CSS length, `columns` number, and optional
>              * `labelsPosition` string of `"aside"` or `"top"`. At least one item is required.
> ```

shouldn't be aligned with attributes above ? `label-position` -> `labelPosition` 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/41)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-form-layout.html, line 187 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/41#-KkQXciHQDj4zaFzNTyd:-KkQZFZA_oDchOISyW1r:b-3bl0dj) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/c6ea74d1d2678c911541c10fa5d9b6f30942908f/vaadin-form-layout.html#L187)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

shouldn't be aligned with attributes above ? `label-position` -> `labelPosition` 
</blockquote></details>

I don’t see `label-position` here. `<vaadin-form-item>`’s attribute is a separate thing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/41)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/41#-:-KkRK8WeS-NIEGkQQmbL:bnfp4nl)*

**Pull request merged**
