### PR TITLE
Add responsive layout support

### LINKED ISSUE #4: Responsive Layout
Specs by @jouni 

Depends on #5 (multiple columns), where “column count” is described.

Column count is reduced at certain breakpoints. The developer can configure those if needed using a property, e.g. `columns`.

The property value format is a comma-separated list of space-separated values of a CSS length and a number, where the CSS length indicates the breakpoint width and the number indicates the column count. The length value can be omitted which equals it to `0`.

The default value for that property is `1, 40em 2` (might change), which means the following:

When the layout width (independent of the browser viewport width) is:
- `< 40em` column count is 1.
- `>= 40em` column count is 2.

More examples:

- `columns="1"` column count is always 1
- `columns="3"` column count is always 3
- `columns="1 3"` column count is always 3
- `columns="3 1"` invalid length (`3` == `0`), column count is always 1
- `columns="1, 400px 2"` column count is 1 below 400px, and 2 above 400px
- `columns="1, 600px 2"` column count is 1 below 600px, and 2 otherwise
- `columns=""` any unrecognized value (including single length values like `123px`) is ignored and equals to `1`.

### PR DESCRIPTION
**Pull request by platosha**
Fixes #4

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-form-layout/15)

### CODE REVIEW

**Comment by Saulis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-form-layout.html, line 130 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15#-Kh6GmhH51cofjXkjdlO:-Kh6GmhIXYHM7o6Jfjkn:b5ir1ve) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/206469b7062bcdda52d4c109457a2a4d041c9e74/vaadin-form-layout.html#L130)):*
> ```HTML
>            * behavior with number of columns depending on the layout width.
>            *
>            * The value is a comma-separated list of one or more reposnsive
> ```

reposnsive -> responsive

---

*[vaadin-form-layout.html, line 186 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15#-Kh6IBFUJ15YUmNSUE-q:-Kh6IBFUJ15YUmNSUE-r:b-6q50ub) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/206469b7062bcdda52d4c109457a2a4d041c9e74/vaadin-form-layout.html#L186)):*
> ```HTML
>         super.connectedCallback();
> 
>         window.addEventListener('resize', this._boundResizeListener);
> ```

I remember you had some prototype using an iframe so that we can react to changes in the container size, was that approach dropped?

---

*[test/form-layout.html, line 79 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15#-Kh6HoFLmySFi21Hc1V-:-Kh6HoFLmySFi21Hc1V0:b-votpkz) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/206469b7062bcdda52d4c109457a2a4d041c9e74/test/form-layout.html#L79)):*
> ```HTML
>       });
> 
>       it('should assing width inline style on items', function() {
> ```

<nipick>typo: "assign"</nitpick>

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15)*

**Comment by tomivirkki** [comment]
*[vaadin-form-layout.html, line 186 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15#-Kh6IBFUJ15YUmNSUE-q:-Kh6I__GS40shMWtPa_k:bhr8u2l) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/206469b7062bcdda52d4c109457a2a4d041c9e74/vaadin-form-layout.html#L186)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

I remember you had some prototype using an iframe so that we can react to changes in the container size, was that approach dropped?
</blockquote></details>

Ooh, we used the iframe approach in `<vaadin-grid>` 1 and in hindsight it was a bit overkill. I'd rather use `IronResizableBehavior` here. It's also used in `<vaadin-grid>` 2.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15)*

**Comment by platosha** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-form-layout.html, line 130 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15#-Kh6GmhH51cofjXkjdlO:-Kh6_m7Oa_nWStT-905_:b-896fix) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/206469b7062bcdda52d4c109457a2a4d041c9e74/vaadin-form-layout.html#L130)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

reposnsive -> responsive
</blockquote></details>

Done.

---

*[vaadin-form-layout.html, line 186 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15#-Kh6IBFUJ15YUmNSUE-q:-Kh6_n3yfQOrtjbAMiwg:b-896fix) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/206469b7062bcdda52d4c109457a2a4d041c9e74/vaadin-form-layout.html#L186)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Ooh, we used the iframe approach in `<vaadin-grid>` 1 and in hindsight it was a bit overkill. I'd rather use `IronResizableBehavior` here. It's also used in `<vaadin-grid>` 2.
</blockquote></details>

Done.

---

*[test/form-layout.html, line 79 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15#-Kh6HoFLmySFi21Hc1V-:-Kh6_oUz3pVsjZdKn_xF:b-896fix) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/206469b7062bcdda52d4c109457a2a4d041c9e74/test/form-layout.html#L79)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

<nipick>typo: "assign"</nitpick>
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15)*

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-form-layout.html, line 21 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15#-Kh6qf8QcwUO40KOyqVB:-Kh6qf8QcwUO40KOyqVC:bb7p4x2) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/8bfae03356de1630b76fd41761cb86662f963be9/vaadin-form-layout.html#L21)):*
> ```HTML
> 
> By default, it makes a layout of two columns if the element width is equal or
> wider then 40em, and a single column layout otherwise.
> ```

than

---

*[vaadin-form-layout.html, line 135 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15#-Kh6sWHIrcG_q2PBzjV4:-Kh6sWHIrcG_q2PBzjV5:bvcav0n) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/8bfae03356de1630b76fd41761cb86662f963be9/vaadin-form-layout.html#L135)):*
> ```HTML
>           /**
>            * Number of columns in the layout. Allows specifying responsive
>            * behavior with number of columns depending on the layout width.
> ```

... a responsive behaviour with the number ...

---

*[vaadin-form-layout.html, line 209 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15#-Kh8Na8XRkYmZbM-wq1M:-Kh8Na8XRkYmZbM-wq1N:bqbaes) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/8bfae03356de1630b76fd41761cb86662f963be9/vaadin-form-layout.html#L209)):*
> ```HTML
>             minWidth: minWidth || 0
>           };
>         });
> ```

I think we should test that the entire syntax of each block is correct, the user could be unnoticed if he made some mistake.

Probably a regex could work better, and you could get rid of the _naturalNumberOrOne method

```
var r = /([1-9]\d+) +(\d+(px|pt|vh|vv))/i.exec(part);
if (r) return {columns: r[1], minWidth: r[2]};
else warn_to_the user and return defaults
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15)*

**Comment by Saulis** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-form-layout.html, line 209 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15#-Kh8Na8XRkYmZbM-wq1M:-KhMhPfrM4-JuHO1TNeA:b-5ges3v) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/8bfae03356de1630b76fd41761cb86662f963be9/vaadin-form-layout.html#L209)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I think we should test that the entire syntax of each block is correct, the user could be unnoticed if he made some mistake.

Probably a regex could work better, and you could get rid of the _naturalNumberOrOne method

```
var r = /([1-9]\d+) +(\d+(px|pt|vh|vv))/i.exec(part);
if (r) return {columns: r[1], minWidth: r[2]};
else warn_to_the user and return defaults
```
</blockquote></details>

+1 for the current approach for readability, I can't even tell if that regex does the same thing or not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15#-:-KhMhl7pTXT3b_oRMi-k:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15#-:-KhMhsgrTw6OhNnAA0lI:bnfp4nl)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-form-layout.html, line 209 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15#-Kh8Na8XRkYmZbM-wq1M:-KhMjWBQ2fz5pOdG1362:bogqinm) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/8bfae03356de1630b76fd41761cb86662f963be9/vaadin-form-layout.html#L209)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

+1 for the current approach for readability, I can't even tell if that regex does the same thing or not.
</blockquote></details>

The main point here is to check that the parameter is correct and warn the user otherwise.
Usage of regex is quite common precisely for readability ;-)  in one line you can deduce that you need a 'natural number not starting with 0' a 'space' and a 'number' followed by  a valid unit 'px, pt, vh, vv' 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15)*

**Comment by platosha** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-form-layout.html, line 21 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15#-Kh6qf8QcwUO40KOyqVB:-KhRIpX7yTKMMjXG2TFo:b-896fix) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/8bfae03356de1630b76fd41761cb86662f963be9/vaadin-form-layout.html#L21)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

than
</blockquote></details>

Done.

---

*[vaadin-form-layout.html, line 135 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15#-Kh6sWHIrcG_q2PBzjV4:-KhRIr3Jzi_EqWD0VTBd:b-896fix) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/8bfae03356de1630b76fd41761cb86662f963be9/vaadin-form-layout.html#L135)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

... a responsive behaviour with the number ...
</blockquote></details>

Done.

---

*[vaadin-form-layout.html, line 209 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15#-Kh8Na8XRkYmZbM-wq1M:-KhRCdrFB30YxuILggOI:b-fd1vcv) ([raw file](https://github.com/vaadin/vaadin-form-layout/blob/8bfae03356de1630b76fd41761cb86662f963be9/vaadin-form-layout.html#L209)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

The main point here is to check that the parameter is correct and warn the user otherwise.
Usage of regex is quite common precisely for readability ;-)  in one line you can deduce that you need a 'natural number not starting with 0' a 'space' and a 'number' followed by  a valid unit 'px, pt, vh, vv' 
</blockquote></details>

@manolo note that your regex does not allow `10` columns and floating point threshold values.

A valid regex here will be a bit longer, more complex and hence less readable. 

Actually, CSS length value definition allows much more, like unit-less `0`, a lot more units, and so on. I would rather use CSS parsing for CSS values instead of inventing a regex. I believe we can warn without using regex as well, if needed.

At this point, I would not bother with better parsing and warnings at all. The format is too uncertain to enforce and is very likely to change soon in a next PR and after DX tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout/15#-:-KhRdEZRzAwfwy_ndQlS:bnfp4nl)*

**Pull request merged**
